version: "3.8"

services:
  mymongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  backend:
    build: ./node-backend
    ports:
      - "8081:8081"
    depends_on:
      - mymongodb
  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data: